# The start symbol is START.

# These two rules are required; choose their weights carefully!
# S1 is the start symbol of the grammar you construct
# S2 is the start symbol of the markov grammar that is the default fallback.
99	START	S1
1	START	S2
# This grammar uses a convention that
#    - terminals are lowercase          (president)
#    - preterminals are capitalized     (Noun)
#    - other nonterminals are all-caps  (NP)
#
# This convention just makes grammars more readable to humans.  Thus:
#
#    - You should follow this convention unless you have a good reason
#      not to.
#
#    - But your *program* should still work with grammars that don't
#      follow this convention.  It should not pay any attention to
#      upper/lower case.  From your program's point of view,
#      if there is at least one rule for rewriting a symbol, then
#      that symbol is a nonterminal and should be rewritten.
#######################

# Rules for creating full sentences.
#1  START   S1
1  S1    ST .
1  S1    ST !
1  S1    is it true that ST ?     # mixing terminals and nonterminals is ok.
1  S1    Q ?

# The basic grammar rules.  Here's what the abbreviations stand for:
#    Q = Question
#    WHEREQ = where question
#    WHOQ = who question without did or will
#    WHOWHATQ = who or what question including did or will
#    YNQ = yes no question sentence
#    ST = sentence type (disregard tense)
#    PRESST = present tense sentence type (at least for the first clause)
#    S  = simple sentence
#    CPS = Complex sentence
#    CP = conjunction phrase
#    NP = noun phrase
#    NAP = noun 'and' phrase
#    VP = verb phrase (disregard tense)
#    PRESVP = present tense verb phrase
#    PASTVP = past tesnse verb phrase
#    VAP = verb 'and' phrase
#    IVP = intransitive verb phrase
#    IVerb = intransitive verb
#    CVerb = a verb that can support a conjunctive phrase as the direct object
#    VerbT = a verb in the present tense
#    PastVerb = a verb in the past tense
#    PP = prepositional phrase
#    AP = adjective phrase
#    Det = determiner (sometimes called "article")
#    Prep = preposition
#    Adj = adjective
#    Adv = adverb
#    C = conjunction
#    CMPNDP = compound phrase (a clause starting with "and" or "but")
#    Cmpnd = compounding words (like "and" or "but")
#    Cnp = conjunction for noun phrases (like "that")
#    PASTVPWNP = "past verb phrase with noun phrase"
#       the set of past tense verb phrases that require a noun phrase to come after them
#    THATASNPST = "that as a noun phrase sentence type"
#       sentence (inside a dependent clause) that has a conjunctive phrase on the lefthand side
#    NOTE: who and what did/will questions are treated as their own category of questions
#       that I'm calling WHOWHATDID
#    WHOWHATDIDST = "who what did sentence type":
#       the sentence types that can be included in who/what did/will questions
#    WHOWHATDIDPRESVP = "who what did present tense verb phrase"
#       the present tense verb phrases that can occur in who/what did/will questions

# Questions:
1   Q   YNQ
1   Q   WHOQ
1   Q   WHEREQ
1   Q   WHOWHATQ # who/what did/will questions

# Yes/No questions involving did/will
1   YNQ        YNQStart PRESST

# Where/Who/What did/will questions
1   WHEREQ     where YNQ
1   WHOWHATQ   WhoWhat YNQStart PRESVP
1   WHOWHATQ   WhoWhat YNQStart WHOWHATDIDST

# Who questions without did/will
1   WHOQ       who PASTVP

# Sentence Types
1   ST     SS CMPNDP
1   ST     SS
1   ST     CP' PASTVPWNP

# The structures of the "sentences" that can follow what/who did/will
# aka: "who what did sentence types"
1    WHOWHATDIDST  NP WHOWHATDIDPRESVP
# Want is special cased as it cannot "normally" be followed by a prepositional phrase
1    WHOWHATDIDST  NP  want PP

# Conjunction (compound) phrases
1   CP     CP'
1   CP     CMPNDP
# stringing two independent clauses together using and or but
1   CMPNDP  Cmpnd SS
1   CMPNDP  Cmpnd THATASNPST
# Create a subordinate clause using "that" followed by a simple sentence
# functions as an alternate type of noun phrase (in a sense)
1   CP'    Cnp SS

# Simple (standard) sentences (for this grammar it's past tense unless in a question)
1   SS  PASTST'
1   SS  PASTST
1   SS  PRESST

1   PASTST'  NP  PASTVP
1   PASTST   NP  PASTIVP

# Sentence structure for present tense sentences (only used within questions)
1   PRESST  NP PRESVP
1   PRESST  NP PRESIVP

# Special case sentence structure for when conjunctive phrases are used as the subject
# of a second clause (complex compound sentences)
1   THATASNPST    Cnp SS PASTVPWNP

# Set for intransitive verbs
1   PASTIVP   PastIVerb
1   PRESIVP   PresIVerb

# The full set of present tense verb phrases
1   PRESVP     VerbT NP
1   PRESVP     PRESVP PRESVAP
1   PRESVAP    Cmpnd PRESVP
1   PRESVAP    Cmpnd PRESST
1   PRESVP     WHOWHATDIDPRESVP
# The subset of verb phrases supported for who/what did/will questions
1   WHOWHATDIDPRESVP  VerbT NP Prep
1   WHOWHATDIDPRESVP  PresCVerb CP'
1   WHOWHATDIDPRESVP  PresPrepVerb PP
1   WHOWHATDIDPRESVP  PresAllVerb
1   WHOWHATDIDPRESVP  PresCVerb
1   WHOWHATDIDPRESVP  WHOWHATDIDPRESVP WHOPRESVAP
1   WHOPRESVAP        Cmpnd WHOWHATDIDPRESVP
1   WHOPRESVAP        Cmpnd WHOWHATDIDST

# Special case for what can have a conjunctive clause as its subject
1   PASTVPWNP VerbFollowingThatClause NP
# Normal rules for past tense verb
1   PASTVP    PastVerb NP
1   PASTVP    PastCVerb CP'
1   PASTVP    PastPrepVerb PP
1   PASTVP    PastPrepVerb
1   PASTVP    PastAllVerb
1   PASTVP    PastCVerb
# Can create compound sentences by following a VP with a compounding word (and/but)
# and a sentence
# Can also string verb phrases together using either and or but
1   PASTVP    PASTVP PASTVAP
1   PASTVAP   Cmpnd PASTVP
1   PASTVAP   Cmpnd PASTST

# Noun Phrase rules:
1    NP     Det Noun
0.5  NP     Proper
1    NP     AP Proper
0.2  NP     NP PP
0.2  NP     NP NAP
# You can string lists of noun phrases together with and, but not with but
1    NAP    and NP

# Prepositional phrase rules:
1      PP  Prep NP
0.05   PP  Prep

# Nouns can have adjective phrases including adverbs and adjectives
# there must always be an adjective between and adverb and a terminal Noun
2.5  Noun  AP Noun

1   AP  Adj
1   AP  Adv AP

# Vocabulary.  Your program can see that "ate" is a terminal
# symbol because there exists no rule for rewriting it.
# Any symbol that can rewrite as a terminal (or a string of
# terminals, like "chief of staff") is called a "preterminal."  Notice
# that a preterminal is a special kind of nonterminal.


1   PastAllVerb PastVerb
1   PastAllVerb PastIVerb

# Past tense "normal" verbs.
1   PastVerb    wanted
1   PastVerb    pickled
1   PastVerb    perplexed
1   PastVerb    understood

1   PastVerb    PastPrepVerb

# Past tense verbs that can support prepositional phrases on their right hand side
1   PastPrepVerb    kissed
1   PastPrepVerb    worked
1   PastPrepVerb    ate

# Past tense intransitive verbs
1   PastIVerb   sighed

# Verbs that can support conjunctive phrases on their lefthand side (as their agent)
1   VerbFollowingThatClause perplexed

# Present tense verbs
1   PresAllVerb VerbT
1   PresAllVerb PresIVerb

1   VerbT    want
1   VerbT    pickle
1   VerbT    perplex

1   VerbT    PresPrepVerb

# Present tense verbs that can support prepositional phrases on their right hand side
1   PresPrepVerb    kiss
1   PresPrepVerb    work
1   PresPrepVerb    eat

# Present tense intransitive verbs
1   PresIVerb    sigh

# Verbs that can support conjuntive phrases (that X) as direct objects
1   PastCVerb    thought
1   PastCVerb    understood

1   PresCVerb    think
1   PresCVerb    understand

# Determiners
4     Det  the
2     Det  a
0.33  Det  every
1     Det  that

# "Normal" Nouns
1   Noun   president
1   Noun   sandwich
1   Noun   pickle
1   Noun   chief of staff
1   Noun   floor
1   Noun   proposal
1   Noun   desk

# Proper Nouns
1   Noun    Proper
1   Proper    Sally

# Adjectives
1    Adj  fine
1    Adj  delicious
0.2  Adj  perplexed
0.5  Adj  pickled

# Prepositions
1   Prep  with
1   Prep  on
1   Prep  under
1   Prep  in

# Connective words
1   C   Cnp
1   C   Cmpnd
1   Cmpnd   but
1   Cmpnd   and
1   Cnp   that

# Adverbs
1   Adv very

# Question words
1   YNQStart     did
1   YNQStart     will
1   WhoWhat      who
1   WhoWhat      what# This is a hand-generated set of preterminal rules.
# It specifies a simple tag set which will be handled by the S2
# grammar and which can (though doesn't necessarily need to be)
# handled by the S1 grammar.
#
# The weights given here may be changed, but no new vocabulary
# items are to be added.

# Miscellaneous items that don't fit into any of our simple tags are
# given to Misc.  You will want to develop your own tags for these!


# Singular and mass nouns.  Notice that only the
# ones that start with consonants get our Noun tag.
1	Noun	castle
1	Noun	king
1	Noun	defeater
1	Noun	sovereign
1	Noun	servant
1	Noun	corner
1	Noun	land
1	Noun	quest
1	Noun	chalice
1	Noun	master
1	Noun	horse
1	Noun	fruit
1	Noun	swallow
1	Noun	sun
1	Noun	winter
1	Noun	coconut
1	Noun	pound
1	Noun	husk
1	Noun	home
1	Noun	weight
1	Noun	story

# Determiners.
1	Det	a
1	Det	another
1	Det	any
1	Det	each
1	Det	every
1	Det	no
1	Det	that
1	Det	the
1	Det	this

# Prepositions.
1	Prep	above
1	Prep	across
1	Prep	at
1	Prep	below
1	Prep	by
1	Prep	for
1	Prep	from
1	Prep	into
1	Prep	near
1	Prep	of
1	Prep	on
1	Prep	over
1	Prep	through
1	Prep	with

# Proper nouns.  Note that our Proper tag is just for people.
1	Proper	Arthur
1	Proper	Guinevere
1	Proper	Sir Lancelot
1	Proper	Sir Bedevere
1	Proper	Zoot
1	Proper	Dingo
1	Proper	Patsy
1	Proper	Uther Pendragon

# Verbs (third person singular present).
# Note that only transitive verbs get our VerbT tag,
# and some of those could also function as intransitives!
1	VerbT	has
1	VerbT	covers
1	VerbT	is
1	VerbT	drinks
1	VerbT	carries
1	VerbT	rides

# End-of-sentence.
1	Misc	!
1	Misc	.
1	Misc	?

# Pauses.
1	Misc	,
1	Misc	...
1	Misc	--
1	Misc	;
1	Misc	:

# Coordinating conjunctions.
1	CC	and
1	CC	but
1	CC	or
1	CC	either
1	CC	nor
1	CC	neither
1	CC	so

# Numbers.
1	Number	eight
1	Number	five
1	Number	one
1	Number	5.5
1	Number	sixty
1	Number	5,000

# Expletive.
1	Misc	there

# Subordinating conjunctions.
1	SC	that
1	SC	so
1	SC	while
1	SC	because
1	SC	if

# Modals.
1	Misc	can
1	Misc	could
1	Misc	may
1	Misc	might
1	Misc	must
1	Misc	ought
1	Misc	shall
1	Misc	should
1	Misc	will
1	Misc	would


# Adjectives.
1	Adj	bloody
1	Adj	weary
1	Adj	unable
1	Adj	trusty
1	Adj	further
1	Adj	sacred
1	Adj	tropical
1	Adj	indigenous
1	Adj	temperate
1	Adj	hot
1	Adj	lucky
1	Adj	simple
1	Adj	tiny
1	Adj	hard
1	Adj	sensational
1	Adj	comparable
1	Adj	angolian
1	Adj	yellow
1	Adj	plodding

# Comparative adjectives.
1	Adj_Compare	bloodier
1	Adj_Compare	wearier
1	Adj_Compare	trustier
1	Adj_Compare	hotter
1	Adj_Compare	simpler
1	Adj_Compare	tinier
1	Adj_Compare	harder

# Superlative adjectives.
1	Adj_Superlative	bloodiest
1	Adj_Superlative	weariest
1	Adj_Superlative	trustiest
1	Adj_Superlative	hottest
1	Adj_Superlative	simplest
1	Adj_Superlative	tiniest
1	Adj_Superlative	hardest

# Plural nouns.
1	Misc	coconuts
1	Misc	halves
1	Misc	snows
1	Misc	mountains
1	Misc	areas
1	Misc	strangers
1	Misc	inches
1	Misc	snakes
1	Misc	ants
1	Misc	nights

# More proper nouns, not people.

1	Misc	Camelot
1	Misc	England
1	Misc	Holy Grail
1	Misc	Round Table

# Plural proper nouns.
1	Misc	Britons
1	Misc	Saxons

# Personal pronouns.
1	Misc	he
1	Misc	her
1	Misc	him
1	Misc	it
1	Misc	one
1	Misc	she
1	Misc	them
1	Misc	they


# Possessive personal pronouns
1	Misc	her
1	Misc	his
1	Misc	its
1	Misc	their

# Adverbs.
1	Adv	again
1	Adv	already
1	Adv	currently
1	Adv	frequently
1	Adv	precisely
1	Adv	south
1	Adv	successfully
1	Adv	unfortunately

# 'do'/'does'
1	Misc	do
1	Misc	does

# 'to'
1	Misc	to

# 'not'
1	Misc	not

# Verbs (base form).
1	Misc	have
1	Misc	speak
1	Misc	cover
1	Misc	be
1	Misc	ride
1	Misc	drink
1	Misc	grow
1	Misc	carry
1	Misc	suggest
1	Misc	migrate
1	Misc	know

# Verbs (past tense).
1	Misc	had
1	Misc	spoke
1	Misc	covered
1	Misc	was
1	Misc	were
1	Misc	rode
1	Misc	drank
1	Misc	grew
1	Misc	carried
1	Misc	suggested
1	Misc	migrated
1	Misc	knew

# Verbs (present participles).
1	Misc	having
1	Misc	speaking
1	Misc	covering
1	Misc	being
1	Misc	riding
1	Misc	drinking
1	Misc	growing
1	Misc	carrying
1	Misc	suggesting
1	Misc	migrating
1	Misc	knowing

# Verbs (past participle).
1	Misc	had
1	Misc	spoken
1	Misc	covered
1	Misc	been
1	Misc	ridden
1	Misc	drunk
1	Misc	grown
1	Misc	carried
1	Misc	suggested
1	Misc	migrated
1	Misc	known

# More third person singular verbs.
1	Misc	speaks
1	Misc	grows
1	Misc	goes
1	Misc	migrates
1	Misc	suggests
1	Misc	knows

# Verbs (present, plural, third person).
1	Misc	have
1	Misc	speak
1	Misc	cover
1	Misc	are
1	Misc	ride
1	Misc	drink
1	Misc	grow
1	Misc	carry
1	Misc	suggest
1	Misc	migrate
1	Misc	know

# Wh-determiners.
1	Misc	that
1	Misc	what
1	Misc	which

# Wh-pronouns.
1	Misc	what
1	Misc	who

# Wh possessive pronoun.
1	Misc	whose

# Wh-adverbs
1	Misc	how
1	Misc	when
1	Misc	where
1	Misc	why


# Possessive marker.
1	Misc	's
